### ISSUE TITLE
Plasma 6: the program interface is larger than the window itself. Hiding the bottom buttons.

### ISSUE THREAD

**Issue by gleyconJ** [mhogomchungu/media-downloader#426] opened 2024-07-17 02:01 UTC
![imagem - 2024-07-16 -- 10 55-1](https://github.com/user-attachments/assets/32f6fe36-a88a-4f42-a2a5-cabffde55ef3)

Hello. I'm using KDE Plasma 6, and it's been months since I've been able to use this program. The reason is what is in the image I posted next to this message.

The buttons at the bottom are hidden by the window limits, and I can't change that in any way.

Could you help me fix this?

Thank you very much for this wonderful project.

**Comment by mhogomchungu** [comment] 2024-07-23 17:39
By design, the app window can not be resized but can be scaled up or down by changing a settings option. This UI option to scale the UI was removed in version 4.8.0 because it was not possible to reset the UI if a user used a wrong option causing the UI to be too big or too small.

To scale down the UI, do the following:-

1. Close Media Downloader.
2. Go to a folder at ```/home/gleycon/.local/share/media-downloader/settings```.
3. Open the settings file inside the folder above with a text editor.
4. Look for the option named EnabledHighDpiScalingFactor and change its value to 0.8.
5. Close the text editor and restart Media Downloader and check the UI has the smaller size you want. Repeat above steps changing scale factor until the UI has the size that works best for you.

**Comment by mhogomchungu** [comment] 2024-07-27 16:52
Closing as "question answered".

**Closed by mhogomchungu** 2024-07-27 16:52 UTC
