### ISSUE TITLE
missing wget and ffmpeg

### ISSUE THREAD

**Issue by TeLLie** [mhogomchungu/media-downloader#104] opened 2022-03-09 18:58 UTC
Hi
I compiled it for OS2 and use qt5 v5.15.2 and gcc 9.2.0
But when running the program i see in log:

[media-downloader] *****************************************************
[media-downloader] To Disable These Checks, Do The Following:-
[media-downloader] 1. Go To "Configure" Tab.
[media-downloader] 2. Go To "General Options" Sub Tab.
[media-downloader] 3. Uncheck "Show Version Info When Starting".
[media-downloader] *****************************************************
[media-downloader] Failed to find executable "wget"
[media-downloader] Error, executable to backend "wget" could not be found
[media-downloader] Failed to find executable "ffmpeg"
[media-downloader] Error, executable to backend "ffmpeg" could not be found
[media-downloader] Failed to find executable "aria2c"
[media-downloader] Error, executable to backend "aria2c" could not be found
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2022.03.08.1
[media-downloader] Checking installed version of youtube-dl
[media-downloader] Found version: 2021.12.17
[media-downloader] Checking installed version of yt-dlp-ffmpeg
[media-downloader] Found version: 2022.03.08.1

Any idea?

**Comment by mhogomchungu** [comment] 2022-03-10 07:16
Bundling happens in Windows only.

Install those missing executables using your system's way of installing executables and Media Downloader should be able to pick them up.

**Comment by TeLLie** [comment] 2022-03-10 07:19
Hi
Thankz for answer, but this is with os/2 to.
I have all in path but it still don't see those.
Also copied to same dir as the exe is , but same..

Op do 10 mrt. 2022 08:17 schreef mhogomchungu ***@***.***>:

**Comment by mhogomchungu** [comment] 2022-03-10 09:46
I think the problem is here[1], os/2 uses window's path separator.

[1] https://github.com/mhogomchungu/media-downloader/blob/7b03de5fd7dfca393685e441705f42aa7f6edcb2/src/engines.cpp#L49

**Comment by mhogomchungu** [comment] 2022-03-10 10:35
Update from git and try again

**Comment by TeLLie** [comment] 2022-03-10 17:29
Hi
I did a git  update
This is output...
weakld: error: Unresolved symbol (UNDEF) '__ZN7utility11python3PathEv'.
weakld: info: The symbol is referenced by:
    D:\temp\ldconv_engines_cpp_o_378622a866512d2a8.obj
weakld: error: Unresolved symbol (UNDEF) '__ZN7utility13platformIsOSXEv'.
weakld: info: The symbol is referenced by:
    D:\temp\ldconv_settings_cpp_o_378622a8649111170.obj
    D:\temp\ldconv_engines_cpp_o_378622a866512d2a8.obj
weakld: error: Unresolved symbol (UNDEF) '__ZN7utility15platformIsLinuxEv'.
weakld: info: The symbol is referenced by:
    D:\temp\ldconv_configure_cpp_o_378622a8659184530.obj
    D:\temp\ldconv_lux_cpp_o_378622a8677165518.obj
weakld: error: Unresolved symbol (UNDEF) '__ZN7utility17platformIsWindowsEv'.
weakld: info: The symbol is referenced by:
    D:\temp\ldconv_settings_cpp_o_378622a8649111170.obj
    D:\temp\ldconv_utility_cpp_o_378622a864b1399e0.obj
    D:\temp\ldconv_about_cpp_o_378622a865017eb58.obj
    D:\temp\ldconv_batchdownloader_cpp_o_378622a865316e1b8.obj
    D:\temp\ldconv_networkAccess_cpp_o_378622a86601952b8.obj
    D:\temp\ldconv_engines_cpp_o_378622a866512d2a8.obj
    D:\temp\ldconv_safaribooks_cpp_o_378622a86711762a0.obj
    D:\temp\ldconv_lux_cpp_o_378622a8677165518.obj
Ignoring unresolved externals reported from weak prelinker.
Error! E2028: __ZN7utility17platformIsWindowsEv is an undefined reference
Error! E2028: __ZN7utility13platformIsOSXEv is an undefined reference
Error! E2028: __ZN7utility15platformIsLinuxEv is an undefined reference
Error! E2028: __ZN7utility11python3PathEv is an undefined reference
file D:/temp\ldconv_settings_cpp_o_378622a8649111170.obj(G:\media-downloader\src\settings.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_settings_cpp_o_378622a8649111170.obj(G:\media-downloader\src\settings.cpp): undefined symbol __ZN7utility13platformIsOSXEv
file D:/temp\ldconv_utility_cpp_o_378622a864b1399e0.obj(G:\media-downloader\src\utility.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_about_cpp_o_378622a865017eb58.obj(G:\media-downloader\src\about.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_batchdownloader_cpp_o_378622a865316e1b8.obj(G:\media-downloader\src\batchdownloader.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_configure_cpp_o_378622a8659184530.obj(G:\media-downloader\src\configure.cpp): undefined symbol __ZN7utility15platformIsLinuxEv
file D:/temp\ldconv_networkAccess_cpp_o_378622a86601952b8.obj(G:\media-downloader\src\networkAccess.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_engines_cpp_o_378622a866512d2a8.obj(G:\media-downloader\src\engines.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_engines_cpp_o_378622a866512d2a8.obj(G:\media-downloader\src\engines.cpp): undefined symbol __ZN7utility11python3PathEv
file D:/temp\ldconv_engines_cpp_o_378622a866512d2a8.obj(G:\media-downloader\src\engines.cpp): undefined symbol __ZN7utility13platformIsOSXEv
file D:/temp\ldconv_safaribooks_cpp_o_378622a86711762a0.obj(G:\media-downloader\src\engines\safaribooks.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_lux_cpp_o_378622a8677165518.obj(G:\media-downloader\src\engines\lux.cpp): undefined symbol __ZN7utility17platformIsWindowsEv
file D:/temp\ldconv_lux_cpp_o_378622a8677165518.obj(G:\media-downloader\src\engines\lux.cpp): undefined symbol __ZN7utility15platformIsLinuxEv
make[2]: *** [media-downloader.exe] Error 1
make[1]: *** [CMakeFiles/media-downloader.dir/all] Error 2
make: *** [all] Error 2

I saw  that u use  platformisOS2 instead of platformIsOS2

Also i use this in utility.cpp

--- G:\media-downloader\src\utility.cpp	2022-03-10 18:13:30.000000000 -0500
+++ G:\media-downloader\src\utility.cpp-os2	2022-03-10 17:59:34.000000000 -0500
@@ -38,17 +38,14 @@
 const char * utility::selectedAction::CLEARSCREEN  = "Clear Screen" ;
 const char * utility::selectedAction::OPENFOLDER   = "Open Download Folder" ;
 
+//#ifdef Q_OS_LINUX
+#if defined(Q_OS_LINUX) || defined(Q_OS_OS2)
+
 bool utility::platformIsOS2()
 {
-#if defined(__OS2__) || defined(OS2) || defined(_OS2)
 	return true ;
-#else
-	return false ;
-#endif
 }
 
-#ifdef Q_OS_LINUX
-
 bool utility::platformIsLinux()
 {
 	return true ;
--- G:\media-downloader\src\utility.cpp	2022-03-10 18:13:30.000000000 -0500
+++ G:\media-downloader\src\utility.cpp-os2	2022-03-10 17:59:34.000000000 -0500
@@ -38,17 +38,14 @@
 const char * utility::selectedAction::CLEARSCREEN  = "Clear Screen" ;
 const char * utility::selectedAction::OPENFOLDER   = "Open Download Folder" ;
 
+//#ifdef Q_OS_LINUX
+#if defined(Q_OS_LINUX) || defined(Q_OS_OS2)
+
 bool utility::platformIsOS2()
 {
-#if defined(__OS2__) || defined(OS2) || defined(_OS2)
 	return true ;
-#else
-	return false ;
-#endif
 }
 
-#ifdef Q_OS_LINUX
-
 bool utility::platformIsLinux()
 {
 	return true ;

**Comment by mhogomchungu** [comment] 2022-03-10 17:55
Your changes will make it fail to compile on windows and MACOS, update from git and it should compile now.

When running from git, did it work?

**Comment by mhogomchungu** [comment] 2022-03-10 17:56
While here, what is the contents of the "PATH" environmental variable in your OS/2 system?

**Comment by TeLLie** [comment] 2022-03-10 18:45
Hi
Yes compiled now.
Only i see its downloading the exe file 
[media-downloader] Start Downloading yt-dlp ... ... ...
[media-downloader] Downloading: https://github.com/yt-dlp/yt-dlp/releases/download/2022.03.08.1/yt-dlp_x86.exe
[media-downloader] Destination: C:/Home/.local/share/media-downloader/bin/yt-dlp_x86.exe.tmp

it should be like before

[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2022.03.08.1
[media-downloader] Checking installed version of youtube-dl
[media-downloader] Found version: 2021.12.17
[media-downloader] Checking installed version of yt-dlp-ffmpeg
[media-downloader] Found version: 2022.03.08[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2022.03.08.1
[media-downloader] Checking installed version of youtube-dl
[media-downloader] Found version: 2021.12.17
[media-downloader] Checking installed version of yt-dlp-ffmpeg
[media-downloader] Found version: 2022.03.08

**Comment by TeLLie** [comment] 2022-03-10 19:47
Oeps, the content of the path enviroment =
PATH=C:\usr\libexec\bin;C:\SYS\BIN;C:\OS2;C:\USR\LOCAL\BIN;C:\USR\SBIN;C:\USR\BIN;C:\IBMLAN\NETPROG;C:\MUGLIB;C:\PROGRAMS\NETSCAPE\PROGRAM;C
:\IBMGSK50\BIN;C:\IBMGSK40\BIN;C:\IBMGSK\BIN;C:\MPTN\BIN;C:\TCPIP\BIN;C:\IBMCOM;C:\OS2\SYSTEM;C:\OS2\MDOS\WINOS2;C:\OS2\INSTALL;C:\;C:\OS2\M
DOS;C:\OS2\APPS;C:\MMOS2\FREEDB;C:\MMOS2;C:\MMOS2\MMPLAYER;C:\PROGRAMS\NDFS;C:\SYS\APPS\4OS2;C:\PROGRAMS\ARCTOOL;C:\PROGRAMS\OPENJDK\BIN;;
The exe files are in usr/bin

**Comment by mhogomchungu** [comment] 2022-03-10 20:50
Try now from git

**Comment by TeLLie** [comment] 2022-03-10 21:10
ok thats fixed 

But still see
[media-downloader] *****************************************************
[media-downloader] Failed to find executable "wget"
[media-downloader] Error, executable to backend "wget" could not be found
[media-downloader] Failed to find executable "ffmpeg"
[media-downloader] Error, executable to backend "ffmpeg" could not be found

**Comment by mhogomchungu** [comment] 2022-03-10 21:33
Are you sure you have ffmpeg installed? What i
Copy "ffmpeg" executable to where Media Downloader is downloding yt-dlp(C:/Home/.local/share/media-downloader/bin/) and restart it and see if it makes a difference.

**Comment by TeLLie** [comment] 2022-03-10 21:45
That makes no diff

C:\Home\.local\share\media-downloader\bin>wget -V
GNU Wget 1.20.3 built on os2-emx.


C:\Home\.local\share\media-downloader\bin>ffmpeg -V
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (GCC)
So those are installed

**Comment by mhogomchungu** [comment] 2022-03-11 06:46
Open the terminal and run "media-downloader --debug" and post the output of those version checks.

It does not make sense why yt-dlp can be found but ffmpeg can not if they are both in the same folder.

**Comment by TeLLie** [comment] 2022-03-11 08:16
Hi
First thankz for helping this out :)

[media-downloader] *****************************************************
[media-downloader] Failed to find executable "aria2c"
[media-downloader] Error, executable to backend "aria2c" could not be found
[media-downloader] Checking installed version of yt-dlp
[media-downloader] cmd: "C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
[media-downloader] Found version: 2022.03.08.1
[media-downloader] Checking installed version of wget
[media-downloader] cmd: "C:/USR/BIN/wget.exe" "--version"
[media-downloader] Found version: 1.20.3
[media-downloader] Checking installed version of youtube-dl
[media-downloader] cmd: "C:/Home/.local/share/media-downloader/bin/youtube-dl" "--version"
[media-downloader] Found version: 2021.12.17
[media-downloader] Checking installed version of yt-dlp-ffmpeg
[media-downloader] cmd: "C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
[media-downloader] Found version: 2022.03.08.1
[media-downloader] Checking installed version of ffmpeg
[media-downloader] cmd: "C:/USR/BIN/ffmpeg.exe" "-version"
[media-downloader] Found version: 4.2.2

**Comment by mhogomchungu** [comment] 2022-03-11 08:33
This commit[1] seems to have fix the issue.

Closing this bug report because the reported issue is now fixed.

[1] https://github.com/mhogomchungu/media-downloader/commit/195e56cc8a0027f32ca0fee20a47b1ba749f4749

**Closed by mhogomchungu** 2022-03-11 08:33 UTC

**Comment by TeLLie** [comment] 2022-03-11 08:36
Yes its workinf fine now
.
Thankz again for all the great help :)

**Comment by TeLLie** [comment] 2023-10-03 20:57
Hi

I compiled latest source but i get...

[media-downloader] Failed to find executable "aria2c.exe"
[media-downloader] Error, executable to backend "aria2c" could not be found
[media-downloader] *************************************************************
[media-downloader] To Disable These Checks, Do The Following:-
[media-downloader] 1. Go To "Configure" Tab.
[media-downloader] 2. Go To "General Options" Sub Tab.
[media-downloader] 3. Uncheck "Show Version Info When Starting".
[media-downloader] *************************************************************
[media-downloader] Download Path: C:/Home/Downloads
[media-downloader] App Data Path: C:/Home/.local/share/media-downloader
[media-downloader] *************************************************************
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Failed to find version information, make sure "ffmpeg" is installed and works properly

Did the source changed ?

**Comment by mhogomchungu** [comment] 2023-10-04 06:17
Update from git and try again and run it from CLI with "--debug" option set.

**Comment by TeLLie** [comment] 2023-10-04 16:34
Hi
If i use cmd line with --debug i get no relevant info...

But when starting i see...

media-downloader] *************************************************************
[media-downloader] Checking installed version of yt-dlp
[media-downloader] cmd: "C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly
[media-downloader] Checking installed version of ffmpeg
[media-downloader] cmd: "C:\USR\BIN/ffmpeg.exe" "-version"
[media-downloader] Failed to find version information, make sure "ffmpeg" is installed and works properly
[media-downloader] Start Downloading yt-dlp ... ...
[media-downloader] Downloading: https://github.com/yt-dlp/yt-dlp/releases/download/2023.09.24/yt-dlp
[media-downloader] Destination: C:/Home/.local/share/media-downloader/bin/yt-dlp.tmp
[media-downloader] Downloading yt-dlp: 2.79 MiB / 2.79 MiB (100.00%)
[media-downloader] Download complete
[media-downloader] Renaming file to: C:/Home/.local/share/media-downloader/bin/yt-dlp
[media-downloader] Checking installed version of yt-dlp
[media-downloader] cmd: "C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
[media-downloader] Failed to find version information, make sure "yt-dlp" is installed and works properly


It seems to download but cannot get version info...

from cmdline i see: 
C:\Home\.local\share\media-downloader\bin>ffmpeg.exe -version gives no info

C:\Home\.local\share\media-downloader\bin>ffmpeg.exe --version 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (GCC)

C:\Home\.local\share\media-downloader\bin>python --version
Python 3.9.17

**Comment by mhogomchungu** [comment] 2023-10-04 16:58
1. So "ffmpeg" works with "--version" and not with "-version", thats easy to fix.
2. I do not see errors with wget.
3. What does below command give you when you run it from the terminal.

```
"C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
```

**Comment by TeLLie** [comment] 2023-10-04 17:47
Hi,

It's the only rpm we have atm, can try to build newer..
Wget is not mention at all, as I have wget installed
The version output 2023.09.24

Run python yt-dlp --version

**Comment by mhogomchungu** [comment] 2023-10-04 18:44
Your comments is not clear what you are getting when you run the following command

```
"C:/Home/.local/share/media-downloader/bin/yt-dlp" "--version"
```

**Comment by TeLLie** [comment] 2023-10-04 19:26
Hi

With os2 we use python yt-dlp --version
And the output is "2023-09.24"

As I run just yt-dlp --version it says "it's not a internal or external
operable program or batch file"

with kind regards,
                                Elbert & Nicole Pol

Op wo 4 okt. 2023 20:44 schreef mhogomchungu ***@***.***>:

**Comment by mhogomchungu** [comment] 2023-10-04 19:51
You can make Media Downloader work with your version of ffmpeg by changing [this](https://github.com/mhogomchungu/media-downloader/blob/e1bb0c31ab23a454f3154fe2815f84125da8bf48/src/engines.cpp#L332) line.

Do the following to make python run yt-dlp.

1. Go to ```C:/Home/.local/share/media-downloader/engines.v1``` folder.
2. Open ```yt-dlp.json``` text file with a text editor.
3. Look at the text file and you will see below section.
4. In the "Args" part, replace ```"yt-dlp"``` text with ``` "python","yt-dlp"``` text,
5. Save the file and restart Media Downloader.
```
"Generic": {
            "amd64": {
                "Args": [
                    "yt-dlp"
                ],
                "Name": "yt-dlp"
            },
            "x86": {
                "Args": [
                    "yt-dlp"
                ],
                "Name": "yt-dlp"
            }
        },
```

**Comment by TeLLie** [comment] 2023-10-05 20:26
Hi,
It's all working again, as it where errors in my env, that makes things not
run properly.. also ffmpeg works with just 1 -

I just rebuild my usr dir.

Sorry for mixed up things...

with kind regards,
                                Elbert & Nicole Pol

Op wo 4 okt. 2023 21:51 schreef mhogomchungu ***@***.***>:

**Comment by TeLLie** [comment] 2023-10-06 15:11
Hi

When I change line 1092 from engines.cpp to platformislikewindows I also
get the wget, included the version info...

with kind regards,
                                Elbert & Nicole Pol

Op do 5 okt. 2023 22:26 schreef Elbert Pol ***@***.***>:

**Comment by mhogomchungu** [comment] 2023-10-06 15:51
Line 1092 in engines.cpp does not point to anything

[9a4f530f8221f36907bbfb78ff0c57c3dd1c/src/engines.cpp#L1092](https://github.com/mhogomchungu/media-downloader/blob/22649a4f530f8221f36907bbfb78ff0c57c3dd1c/src/engines.cpp#L1092)

**Comment by TeLLie** [comment] 2023-10-06 16:24
Hi

Oeps it's line 2097

with kind regards,
                                Elbert & Nicole Pol

Op vr 6 okt. 2023 17:52 schreef mhogomchungu ***@***.***>:
