### ISSUE TITLE
Number that will be increased with each download, starting at 1, 2, 3 not working properly

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#190] opened 2022-10-06 06:34 UTC
Number that will be increased with each download, starting at 1, 2, 3 doesn't work properly on 
`"%(autonumber)s"` or `"%(playlist_index)s"`
![image](https://user-images.githubusercontent.com/36833664/194230217-5a76383e-dcf2-47a6-abdf-96be53f3c2ab.png)
![image](https://user-images.githubusercontent.com/36833664/194231043-3274fb31-364f-44cd-bcc1-57a8d3d51dc3.png)
like 1- 1- 1- or 1- 2- 1-

**Comment by mhogomchungu** [comment] 2022-10-06 07:03
Where do you put these variables?

**Comment by candrapersada** [comment] 2022-10-06 07:06
playlist downloader tab.

**Comment by candrapersada** [comment] 2022-10-06 07:11
when resuming a failed download the number changes from 3 to 1

**Comment by mhogomchungu** [comment] 2022-10-06 07:26
It works as expected when you populate the playlist and then downloading it all. 

The numbering will be wrong when resuming failed download or when adding new entries to the list and then downloading them or when downloading them manually in any order or when downloading them in any other way other than what is mentioned in the first paragraph.

Didn't think of these other scenarios when adding the functionality.

**Comment by mhogomchungu** [comment] 2022-10-06 08:17
Fixed with [this](https://github.com/mhogomchungu/media-downloader/commit/ba92c3d4f2a78eeb2f11534748a4d4d0dd0dcc51).

![Screenshot_20221006_111005](https://user-images.githubusercontent.com/3496115/194259329-4629ce51-39d6-479c-a56f-52c4626d7e0b.png)

**Closed by mhogomchungu** 2022-10-06 08:17 UTC

**Comment by candrapersada** [comment] 2022-10-06 08:21
why is there no 1?

**Comment by mhogomchungu** [comment] 2022-10-06 08:42
I noticed numbering of file names starts at number 2 after i posted the picture and the problem is now fixed and numbering starts at number 1 as expected.

![Screenshot_20221006_113948](https://user-images.githubusercontent.com/3496115/194265016-130423a2-8ab6-4a2a-be84-85bbeff9d649.png)

**Comment by candrapersada** [comment] 2022-10-06 09:15
`--playlist-items 3-5` 1 2 3?
and add `--autonumber-start 3`
![image](https://user-images.githubusercontent.com/36833664/194274322-60b4b1a7-d50f-4cf2-ab31-fa2381bdbb8f.png)

**Comment by mhogomchungu** [comment] 2022-10-07 05:19
Auto number option is now supported.
