### ISSUE TITLE
yt-dlp reports SSL: CERTIFICATE_VERIFY_FAILED when using media-downloader, but no error if running in regular terminal

### ISSUE THREAD

**Issue by Xdminsy** [mhogomchungu/media-downloader#404] opened 2024-05-21 20:46 UTC
It reports.

```
[youtube] Extracting URL: https://www.youtube.com/watch?v=TxcZgrQ2dqw
[youtube] TxcZgrQ2dqw: Downloading webpage
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

I'm not sure why this happens, I'm using a proxy, and media-downloader used to work fine before.

I copied the command of yt-dlp in media-downloader textbox and ran the command myself in cmd and powershell, it worked fine too, no error and downloaded the video successfully. Not sure why the same command that reports the CERTIFICATE_VERIFY_FAILED in media-downloader.

The versions.
```
[media-downloader] *************************************************************
[media-downloader] Checking installed version of OpenSSL
[media-downloader] Found version: OpenSSL 1.1.1j  16 Feb 2021
[media-downloader] Checking installed version of Media Downloader
[media-downloader] Found version: 4.6.0
[media-downloader] Checking installed version of yt-dlp
[media-downloader] Found version: 2024.04.09
[media-downloader] Checking installed version of aria2c
[media-downloader] Found version: 1.37.0
[media-downloader] Checking installed version of wget
[media-downloader] Found version: 1.21.3
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: n7.0-7-gd38bf5e08e-20240409
```

**Comment by Xdminsy** [comment] 2024-05-22 06:03
```
[media-downloader] cmd: "D:/mine/Portable/Media/MediaDownloader/local/bin/yt-dlp.exe" "--proxy" "127.0.0.1:1081" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=TxcZgrQ2dqw"
[youtube] Extracting URL: https://www.youtube.com/watch?v=TxcZgrQ2dqw
[youtube] TxcZgrQ2dqw: Downloading webpage
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] TxcZgrQ2dqw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by mhogomchungu** [comment] 2024-05-22 07:05
This makes no sense.

I see you are using a portable version, copy the folder to your desktop and run it from there and see if it will make a difference.

**Comment by Xdminsy** [comment] 2024-05-22 07:08
Okay, I see it's same.

```
[media-downloader] cmd: "C:/Users/x/Desktop/MediaDownloader/local/bin/yt-dlp.exe" "--proxy" "127.0.0.1:1081" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=TxcZgrQ2dqw"
[youtube] Extracting URL: https://www.youtube.com/watch?v=TxcZgrQ2dqw
[youtube] TxcZgrQ2dqw: Downloading webpage
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] TxcZgrQ2dqw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[media-downloader] Download Failed(ErrorCode=1)
```

**Comment by mhogomchungu** [comment] 2024-05-22 07:24
Add "--verbose" in the ```Download Options``` text field and try again and post output, maybe there is something in the logs that will give us a clue. Run the command again from the terminal and post its output too.

**Comment by Xdminsy** [comment] 2024-05-22 07:39
Oh sorry, you're right, now my command line has this error too and same result in media-downloader.
And I figured out why my terminal command succeeded before.

I see that I got this error, but after I define environment variable HTTP_PROXY and HTTPS_PROXY to "http://127.0.0.1:1081", then they succeed, not sure why the "--proxy" option doesn't work, I try to change "127.0.0.1:1081" to "http://127.0.0.1:1081" but same error, maybe it's a yt-dlp error, I'm sure it's not media-downloader problem now.

Media-downloader.
```
[media-downloader] cmd: "C:/Users/x/Desktop/MediaDownloader/local/bin/yt-dlp.exe" "--verbose" "--proxy" "127.0.0.1:1081" "--newline" "--ignore-config" "--no-playlist" "-o" "%(title).200s-%(id)s.%(ext)s" "--output-na-placeholder" "NA" "-f" "bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "https://www.youtube.com/watch?v=TxcZgrQ2dqw"
[debug] Command-line config: ['--verbose', '--proxy', '127.0.0.1:1081', '--newline', '--ignore-config', '--no-playlist', '-o', '%(title).200s-%(id)s.%(ext)s', '--output-na-placeholder', 'NA', '-f', 'bestvideo[ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best[ext=mp4]/best', '--compat-options', '2022', '--progress-template', 'download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s', 'https://www.youtube.com/watch?v=TxcZgrQ2dqw']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out gbk (No VT), error gbk (No VT), screen gbk (No VT)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_x86_exe)
[debug] Compatibility options: manifest-filesize-approx, playlist-match-filter, prefer-legacy-http-handler, no-external-downloader-progress
[debug] Python 3.8.10 (CPython AMD64 32bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n7.0-7-gd38bf5e08e-20240409 (setts), ffprobe n7.0-7-gd38bf5e08e-20240409
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'all': '127.0.0.1:1081'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=TxcZgrQ2dqw
[youtube] TxcZgrQ2dqw: Downloading webpage
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] TxcZgrQ2dqw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\youtube.py", line 4079, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4043, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 3733, in _extract_player_responses
[media-downloader] Download Failed(ErrorCode=1)
```

cmd
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=TxcZgrQ2dqw
[youtube] TxcZgrQ2dqw: Downloading webpage
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading android player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] TxcZgrQ2dqw: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (1/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (2/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131). Retrying (3/3)...
[youtube] TxcZgrQ2dqw: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] TxcZgrQ2dqw: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Xdminsy** [comment] 2024-05-22 07:47
I checked https://github.com/yt-dlp/yt-dlp/issues/6892 before, and tried `--compat-option no-certifi --no-check-certificate` too then the error goes 404 and some 400 bad request, not sure what's happening :(

**Comment by mhogomchungu** [comment] 2024-05-22 07:48
You said it used to work before.

What proxy option do you have set in the ```Configure```->```Proxy Settings``` tab?

**Comment by Xdminsy** [comment] 2024-05-22 07:58
"Use manually Specified Proxy Configuration" and always "127.0.0.1:1081", the default port that v2rayn use.

I downloaded 4.5 last month, namely 2024.04.28, and I downloaded a video from youtube, and installed several plugins.

Then today I wanted to download another one, open media-downloader it self-update to 4.6, I didn't change anything just pasted the URL and downloaded then it appeared such errors, I tried to download back a 4.5 and disabled updating, using 4.5 still the same error.

I think I must have defined proxy before my first download, I cannot access youtube directly in China. I now tried the 4 options in Proxy Settings, all the same error, don't know why :(.

Oh yes, the No Proxy reports certificate_verify_failed too, I think maybe the `--proxy` option seems to not working.

**Comment by Xdminsy** [comment] 2024-05-22 08:07
Now I tried setting http_proxy and https_proxy then open media-downloader, the "No Proxy"/"Use System Proxy Configuration"/"Get Proxy Configuration From The Environment" work and no such errors.

And "Use System Proxy Configuration" will add "--proxy" "127.0.0.1:1081" options.
"Get Proxy Configuration From The Environment"  adds "--proxy" "http://127.0.0.1:1081" options.

But "Use manually Specified Proxy Configuration" with neither "127.0.0.1:1081" nor "http://127.0.0.1:1081" work.
Weirdly enough :D.

**Comment by mhogomchungu** [comment] 2024-05-22 09:20
What values are you setting in "http_proxy" and "https_proxy".

Try manually specifying proxy address of "https://127.0.0.1:1081" and see if it makes a difference.

**Comment by mhogomchungu** [comment] 2024-05-22 11:50
>Now I tried setting http_proxy and https_proxy then open media-downloader, the "No Proxy"/"Use System Proxy Configuration"/"Get Proxy Configuration From The Environment" work and no such errors.

When you set "No Proxy", do you still get thumbnail in batch downloader/playlist downloader?.

The proxy option is sent to yt-dlp but also to QtNetwork so its better to use other options other than ""No Proxy" if it makes no difference to yt-dlp.

There are some websites(porn mostly) that were blocked in my country when i developed the feature but they are no longer blocked for whatever reason so i can not test the behavior you are seeing.

**Comment by mhogomchungu** [comment] 2024-05-22 14:10
SIn summary, yt-dlp works with a proxy server when the proxy server address is set as an environmental variable and not when it is set using "--proxy" option.

Closing this one since the problem is not caused by Media Downloader. I hope you will open a bug report with yt-dlp project so that they can fix the problem.

**Closed by mhogomchungu** 2024-05-22 14:10 UTC

**Comment by Xdminsy** [comment] 2024-05-22 14:13
Yes I think it's a yt-dlp problem, thank you very much for your patience :)
