### ISSUE TITLE
[BUG]: Videos downloaded go to the Flatpak data folder

### ISSUE THREAD

**Issue by mak448a** [mhogomchungu/media-downloader#440] opened 2024-08-19 13:17 UTC
When downloading a video on the Flatpak version, it goes to `~/.var/app/io.github.mhogomchungu.media-downloader/data/media-downloader/Downloads/` instead of `~/Downloads`.

**Comment by mhogomchungu** [comment] 2024-08-19 13:44
This is by design and i am aware of this "strange default".

If "xdg desktop portal" is broken for whatever reason then "~/Downloads" will point to an imaginary place that disappears when the app is closed and this is very confusing to me as somebody whose desktop starts with a broken "xdg desktop portal" and i have to manually fix it. The default place will always work regardless of the state of desktop portal.

The latest version is the first version that support flatpak and i will change the default to your suggestion location which is the correct default location when i am confident i have addressed all issues related to flatpak support.

You can change the download location by following steps in the below image.

![Screenshot_20240819_162505](https://github.com/user-attachments/assets/bc928c6f-a36f-4d22-9193-5f0530442d5d)

**Comment by mhogomchungu** [comment] 2024-08-19 16:02
I revisited this issue and it looks like the problem was not with xdg desktop portal but with "XDG_DOWNLOAD_DIR" variable being empty in my session,.

The issue is fixed now.

**Closed by mhogomchungu** 2024-08-19 16:02 UTC

**Comment by mak448a** [comment] 2024-08-19 18:38
So in the next update, will it be in the actual Downloads folder?

**Comment by mhogomchungu** [comment] 2024-08-20 12:56
Yes,
New version is out and a flatpak update should be up shortly.

https://github.com/mhogomchungu/media-downloader/releases/tag/5.0.1
