### ISSUE TITLE
Error installing you-get

### ISSUE THREAD

**Issue by FabianLoRs** [mhogomchungu/media-downloader#423] opened 2024-07-03 15:47 UTC
Hello, I can't install you-get, this error appears:

```[media-downloader] *************************************************************
[media-downloader] Checking installed version of bsdtar
[media-downloader] Found version: 3.6.1
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: n7.0-7-gd38bf5e08e-20240409
[media-downloader] Checking installed version of python
[media-downloader] Found version: 3.8.10
[media-downloader] Checking installed version of you-get
[media-downloader] *************************************************************
[media-downloader] Failed to find version information, make sure "you-get" is installed and works properly
[media-downloader] Cmd: "C:/Users/*****/AppData/Roaming/media-downloader/update/3rdParty/python/python.exe" "-u" "C:\Users\*****\AppData\Local\Programs\Python\Python311\Scripts\/you-get.exe" "--version"
[media-downloader] Exit Code: 1
[media-downloader] Exit Status: Normal Exit
[media-downloader] Std Out: Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\****\AppData\Local\Programs\Python\Python311\Scripts\\you-get.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'you_get'

[media-downloader] *************************************************************```

cheers

**Comment by mhogomchungu** [comment] 2024-07-03 19:37
I can not reproduce on windows 10, you are using what version of Windows?

![Screenshot_20240703_223311](https://github.com/mhogomchungu/media-downloader/assets/3496115/4395ea7b-02f8-4d1e-9d4a-9f92f9033e76)

**Comment by mhogomchungu** [comment] 2024-07-03 20:48
A wrong version of you-get seems to be picked up in your system, the correct version is supposed to be at 
```
"C:/Users/****/AppData/Roaming/media-downloader/bin/you-get/you-get"
```
From where did you get you-get? you-get from below github account is a python script and not an exe file like in your cause.

https://github.com/soimort/you-get

**Comment by mhogomchungu** [comment] 2024-07-09 17:34
Closing this one as "local problem".

**Closed by mhogomchungu** 2024-07-09 17:34 UTC
