### ISSUE TITLE
Worst audio

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#108] opened 2022-04-26 00:01 UTC
Hello, Media_Download is amazing and wonderful ! Thank you very much ! 
Please it will be great if there an option preset to choose  by default to download the worst audio quality for a faster download, and possiblity to choosing the native audio quality "opus" or "m4a" without conversion to mp3,  thank you very much !

**Comment by mhogomchungu** [comment] 2022-04-26 05:24
You can do it yourself by following the instructions from here[1]
Steps to do it are:-
1. Go to configure tab.
2. Go to preset option.
3. In the ```UiName``` field, add ```worstaudio``` or any other string of your choice.
4. In the ```Options``` field, add ```worstaudio```.
5. Click ```Add```.
6. Finally, click ```Save```.
7. Go back to ```Basic``` or ```Batch``` downloader tab and click ```Options``` and select your preset option.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#2-how-to-add-custom-commands-to-preset-list

**Comment by trimechee** [comment] 2022-04-26 09:29
Thank you very much for your precious help! and if we want to download the worst video quality, we should add "worstvideo"?

I have a suggestion please: it will be great and more comfortable and faster to add a button "paste from clipboard" and another option "automatically paste from clipboard", and an option "exit after dowloads complete" to automatically close Media-Downloader after finishing downloading all the videos !

I also noticed that when I click on the "libraray" tab, the program freezes completely :(

I wonder if Media-Downloader uses the special version of FFmpeg to avoid bugs? because there is a special builds of FFmpeg for yt-dlp to fix some bugs, it will be great if YouTua can add ann update automatically this special builds of FFmpeg to fix some bugs for example

[Fix AAC HLS streams being truncated mid stream]

[Fix for YouTube's VP9 encodes with non-monotonous DTS]


https://github.com/yt-dlp/FFmpeg-Builds

I use another program to automatically download the worst audio quality of youtube videos and I always get the audio quality with "opus" format with 64kbps bitrate, but using Media-Dowloader the worst audio quality has an "m4a" audio format, with a bitrate of 128kbps, and we would like to have a worse audio quality because I put these audios in my smaprtphone using the "snapdrop.net" sharing site and I would like to preserve the battery of smartphone by using the most worst audio quality, it will be great to add the "opus" 64kb/s audio format for the "worstaudio" preset!

Thank you so much for this wonderful software jewel of technology the best software in the world  !

**Comment by mhogomchungu** [comment] 2022-04-26 10:05
> I have a suggestion please: it will be great and more comfortable and
> faster to add a button "paste from clipboard" and another option
> "automatically paste from clipboard", and an option "exit after dowloads
> complete" to automatically close Media-Downloader after finishing
> downloading all the videos !
>
Batch downloader tab already has a button to paste clipboard contents and
see this[1] bug report to see how to enable automatically pasting clipboard
contents.

[1] https://github.com/mhogomchungu/media-downloader/issues/90

I also noticed that when I click on the "libraray" tab, the program freezes
> completely :(
>
You are using windows I assume?

I wonder if Media-Downloader uses the special version of FFmpeg to avoid
> bugs? because there is a special builds of FFmpeg for yt-dlp to fix some
> bugs, it will be great if YouTua can add ann update automatically this
> special builds of FFmpeg to fix some bugs for example
>
> [Fix AAC HLS streams being truncated mid stream]
>
> [Fix for YouTube's VP9 encodes with non-monotonous DTS]
>
> https://github.com/yt-dlp/FFmpeg-Builds
>
> I use these for bundled version of ffmpeg on windows.

>
> I use another program to automatically download the worst audio quality of
> youtube videos and I always get the audio quality with "opus" format with
> 64kbps bitrate, but using Media-Dowloader the worst audio quality has an
> "m4a" audio format, with a bitrate of 128kbps, and we would like to have a
> worse audio quality because I put these audios in my smaprtphone using the "
> snapdrop.net" sharing site and I would like to preserve the battery of
> smartphone by using the most worst audio quality, it will be great to add
> the "opus" 64kb/s audio format for the "worstaudio" preset!
>
The option of "worstaudio" by itself causes yt-dlp to download whatever it
thinks is the worst. You can add further options to tell to either pick the
worst option of a specific type or download whatever it thinks it's the
worst and then re encode it locally.

When I get back to my computer, I will investigate what options to pass to
yt-dlp to give you the file you prefer.

>
>

**Comment by trimechee** [comment] 2022-04-26 11:46
Ohhh great ! thank you very much for your help and efforts ti make all these wonderful options :)

Yes, I use windows 10 but I have a HDD that is 5 years old, that causes perhaps this slowness and the freeze when I click on "library", I have an intel i3 processor but "library" probably freezes my disk drive because it is slow, maybe disable the "library" tab for notebooks that are old or with little power......

It will also be wonderful please for more fluidity and speed to be able to disable automatic updates when we launch the software and have the option to manually update the software, or option to check the update every week and not each time we launch the software.....


 I use "3D Youtube Downloader" and on the download button arrow, I choose 32kbps audio, and I always get the audio with 64kbps opus format, I think every youtube video has "ogg" audio format, and so the "3D Youtube Downloader" software automatically changes the name of "ogg" audio format to "opus" audio format so that the downloaded audio files can be played by popular audio players like foobar2000, dopamine....and we hope that our beloved " Media-Downloader" can do the same!

https://yd.3dyd.com/


Thank you very much :)

**Comment by trimechee** [comment] 2022-04-26 11:51
Oops, I was responding to your last message but I can't find your answer anymore which has apparently been deleted, I posted my answer anyway and sorry for the delay :)

**Comment by mhogomchungu** [comment] 2022-04-26 12:06
I deleted my comment because i wanted to re-write it in a properly formatted  text and it looks like you read it already so i wont repost it.

Lets continue from your last comment

>Yes, I use windows 10 but I have a HDD that is 5 years old, that causes perhaps this slowness and the freeze when I click on "library", I have an intel i3 processor but "library" probably freezes my disk drive because it is slow, maybe disable the "library" tab for notebooks that are old or with little power......

The library tab scans all files and folder in the  configured download folder to display them and it takes a very long time to complete if the the folder has too many files. How many files and folders are in the configured downloading folder? If its only a handful then the problem is something else.

>It will also be wonderful please for more fluidity and speed to be able to disable automatic updates when we launch the software and have the option to manually update the software, or option to check the update every week and not each time we launch the software.....

There is no automatic updating. The first time around, it automatically downloads missing executables and make sure they work. If you want to update them then you have to manually go to configure tab and update them.

You can and you should disable automatic checking of program version on every startup after you have make sure all installed binaries work as expected.

>I use "3D Youtube Downloader" and on the download button arrow, I choose 32kbps audio, and I always get the audio with 64kbps opus format, I think every youtube video has "ogg" audio format, and so the "3D Youtube Downloader" software automatically changes the name of "ogg" audio format to "opus" audio format so that the downloaded audio files can be played by popular audio players like foobar2000, dopamine....and we hope that our beloved " Media-Downloader" can do the same!

Youtube does not offer audio files in mp3 format and yet, Media Downloader has a default preset option to download audio in mp3 format! What happens is that Media Downloader tells yt-dlp to download an audio file in its default format and then convert it locally to preffered format and bitrate and you can do the same.

The core value of Media Downloader says "You don't have to ask me to make it do what you want" and i go to a great length to give GUI ability to pass options you want to yt-dlp.

Will investigate what preset option you can create to tell Media Downloader to download and convert an audio file to  64kbps opus format

**Comment by trimechee** [comment] 2022-04-26 12:20
Thank you so much !
Yesss  the configured download folder has a size of more than 35Gb, I have downloaded a lot of audio files for years to put them when I sleep.... maybe I have to choose another empty folder....


I don't want to download the audio with "mp3" format, because this format is outdated and outdated and the open source "opus" format has better quality and compression with reasonable size, i checked and the software I use "3D Youtube Downloader" does not convert and apparently it only downloads dash audio formats, maybe it just changes the name of "m4a" or "webm" audio formats to "opus" format. ....

Yesss thank you very much for your kindness and generosity to investigate about this preset option because it is the most important option for me and may be for many others !

Thank you very much !

**Comment by mhogomchungu** [comment] 2022-04-26 15:59
To download audio file in opus format, do the steps i listed in my first comment and in step 4, add ```worstaudio -x --audio-format opus --audio-quality 64K```

Internet says FFmeg does not seem to support adding abr to opus so the ```--audio-quality``` option will be ignored but add it for completeness sake. This also explains your comment where you said you were setting abr of 32kbps but you are getting 64kbps when using "3D Youtube Downloader"

>Some questions please, in "batch donwloader", there is no "monitor clipboard for url"

The feature is already implemented but it is not yet in the released version and will be there with the next released version. You are using Windows or Linux?

>There is option "maximum cucnurrent downloads", that's awesome ! but is there option to limit the number of connection threads per donwload to avoid banishment ?

I believe yt-dlp by default uses one network connection by instance so the number of network connections by default are equal to a number of instances that are running.

>Is it possible to add the option "exit Media-Downloader" after all downloads finsih?

Its possible, put this in its own bug report for easy tracking.

>use the special FFmpeg version of yt-dlp please? the size of the special version of FFmpeg made by yt-dlp is 96mb so i guess Media-Dowloader doesn't use this special version of FFmpeg, , does Media-Downloader automatically download FFmpeg and its update or do we have to install FFmpeg ourselves?

On Windows, Media Downloader ships with its own ```bundled``` version of ffmpeg and it uses the ones from yt-dlp. In other platforms it uses whatever is installed. The bundled version get updated from time to time when i make new releases.

>I set scale factor to the value "3", and when I wanted to restore the default value "1", I could not access the scale factor parameter because the window was too large and the parameter inaccessible, so I I had to uninstall the program and search in the hidden folders of windows appdata ...... to delete and reset Media-Dowloader, it will be good if this process becomes easier or the window becomes scrollable, or have the "reset" button " at the very top of the main window

Put this in its own bug report for easier tracking.

> what does mean "use system excecutables if available" ?

This is for Linux only, binaries Media Downloader downloads are for its own private use, but in linux, it offers an option to use system provided executable instead and  does not download/use its own private version if the system version is available.

On Windows, it unconditionally use its own private version.

> and if we unchek "show version info when starting", there is no more updates ?

The feature does not do updating. All it does is a sanity check to make sure executables are installed and they work as expected. Disable the sanity check and then delete one of the executable and things will not work as expected and you may get unexplained hangs.

**Comment by trimechee** [comment] 2022-04-26 16:17
OHHH thank you very much for these clarifications! I was desperately looking for a reliable open source alternative for "firedm" donwload manager because its repository got deleted in a strange and sudden way and I tried several programs and I can say that your Media-Downloader software is the best of the best of universe!
I use the last version of windows 10.
I contacted the popular "videohelp" that adds your software!

https://www.videohelp.com/software/media-downloader


Thank you so much for you precious help!

**Comment by mhogomchungu** [comment] 2022-04-26 18:58
First time i am hearing of "firedm" and it is strange how the author decided to just delete it.

Thanks you for your post about my application to that website.

**Comment by mhogomchungu** [comment] 2022-04-26 19:04
Closing this one. If i missed anything or if you need further clarification about anything then open another bug report and put it there.

**Closed by mhogomchungu** 2022-04-26 19:04 UTC

**Comment by trimechee** [comment] 2022-04-26 19:08
it was called "pyidm" then it change the name to "firedm", many articles talked about this program like ghacks, korben..... and i asked the author to make new options and he is nice and helpful, i remember youtube-dl got banned from github due to dmca copyright complaint.....firedm is one of the best software and maybe also copyright holders called for it to be removed, it's weird, maybe I'll try to send an email to the author of the program:

https://pypi.org/project/FireDM/

**Comment by trimechee** [comment] 2022-04-26 19:17
Thank you :) 
I tried with the new preset worstaudio opus 64kbps  and it works! thank you so much !

I noticed that it says "post-processing" after downloading the opus audio, does Media-Downloader convert to the opus format? if so, it can consume resources and time, can we add a preset to download the dash audio without conversion, for exemple add a preset to download "ogg" format by default , or "flac", "webm" audio format to avoid conversion and post-processing ?

can I add this preset? worstaudio -x --audio-format ogg webm --audio-quality 64K ?

Thank you !

**Comment by mhogomchungu** [comment] 2022-04-26 20:15
>I noticed that it says "post-processing" after downloading the opus audio, does Media-Downloader convert to the opus format?

1. Media Downloader just gathers options from user and pass them on to yt-dlp.
2. Yt-dlp downloads the media and if "-x" option is given, it passes the downloaded media to ffmpeg for further processing.
3. If you want to download the worstaudio file that is already in opus codec and not want to do further processing, use ```worstaudio[acodec=opus]``` in step 4 from my first comment. A file with this codec must exist or yt-dlp will give an error that says there is no file with that codec to download.

**Comment by trimechee** [comment] 2022-04-26 20:55
Great !! Thank you very much :)
