### ISSUE TITLE
Media Downloader v5.2.0 in Windows 11

### ISSUE THREAD

**Issue by tnilzon** [mhogomchungu/media-downloader#480] opened 2024-11-08 09:14 UTC
Virus detection for MediaDownloader-5.2.0.setup.exe in Windows 11. The file is removed by Windows Defender, and can not be installed.

![image](https://github.com/user-attachments/assets/42862a77-0898-4575-adb9-a6e8e02b453f)

**Comment by Haikel-G** [comment] 2024-11-08 11:14
On Windows 10 too

**Comment by mhogomchungu** [comment] 2024-11-20 17:26
Duplicate of https://github.com/mhogomchungu/media-downloader/issues/481

Closing this one since the other one has comments already.

**Closed by mhogomchungu** 2024-11-20 17:26 UTC
