### ISSUE TITLE
Fails to download Youtube-DL on first run

### ISSUE THREAD

**Issue by slider6996** [mhogomchungu/media-downloader#20] opened 2021-05-04 02:53 UTC
hello, just seeing if im brain farting on something as when i run Media Downloader it errors when trying to download Youtube-DL, exact message it says is 

[media-downloader] Running in portable mode
[media-downloader] Download path: C:/Users/Slider/Desktop/ytd
[media-downloader] Start Downloading youtube-dl ... ...
[media-downloader] Download Failed: TLS initialization failed
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: 4.3.2-2021-02-27-full_build-www.gyan.dev

I tried the non portable version too and have same issue, i see no other issues posted regarding this so i feel like im just simply doing something wrong. Any help be appreciated thank you.

**Comment by mhogomchungu** [comment] 2021-05-04 05:34
Using the portable version, create a text file named ```media-downloader.exe.local``` and try again. Windows has a habit of adding a hiddent ."txt" file extension so pay attention to this, the file must be named ```media-downloader.exe.local```.

A bit of googling led me to this[1[ windows doc that suggests the problem is caused by using an already loaded library instead of the shipped local library and the solution of creating the text file is suggested here[2]

[1] https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications

[2] https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-redirection

**Comment by mhogomchungu** [comment] 2021-05-04 13:35
Try this[1] portable version and see if it works. The app now check for installed version of OpenSSL and should report the bundled version as seen in the image below

![Screenshot_20210504_162445](https://user-images.githubusercontent.com/3496115/117011625-ae3b8280-acf6-11eb-9c39-92d4b93015f8.png)

[1] https://github.com/mhogomchungu/media-downloader/releases/download/1.3.0/MediaDownloader-1.3.0a.zip

**Comment by slider6996** [comment] 2021-05-04 19:45
Just got back home, sorry went to bed last night and didnt see the replies, I first added the file manually and it was still a no go, so downloaded the 1.3.0a that already has the file and still same error, kinda stumped as to why im having this issue as its obviously not a common one so its something on my end i feel like. 

I did have a version of youtube-dl awhile ago that was uninstalled that i think is called now Youtube Downloader 7? I could be wrong on name, idk if that would effect anything but ya still no dice on both fixes. Here is log again below.

[media-downloader] Running in portable mode
[media-downloader] Download path: C:/Users/Slider/Desktop/MediaDownloader-1.3.0a/Downloads
[media-downloader] Checking installed version of OpenSSL
[media-downloader] Found version: 
[media-downloader] Start Downloading youtube-dl ... ...
[media-downloader] Download Failed: TLS initialization failed
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: 4.3.2-2021-02-27-full_build-www.gyan.dev

**Comment by mhogomchungu** [comment] 2021-05-04 20:01
I will try to somehow try to reproduce this locally, in the mean time, go to youtube-dl download page here[1] and download the window's version and put it in the ```local/bin``` folder located in the application folder and restart Media Download to pick it up. Did it work?

Do you know of any program you have installed that may interfere with openssl?

[1] https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.26

**Comment by mhogomchungu** [comment] 2021-05-04 22:47
Try again with below build which uses updated version of openssl(1.1.1j), the earlier version that did not work for you was 1.1.1c. The Qt version Media Downloader is using is 5.15.1 and this version was build with version 1.1.1g of openssl but Qt do not provide it in their maintenance tool.

https://github.com/mhogomchungu/media-downloader/releases/download/1.3.0/MediaDownloader-1.3.0b.zip

**Comment by slider6996** [comment] 2021-05-05 04:09
Hmm ya im not sure of any other programs i use that would cause issues, i did notice in the above screen shot posted that when it gets to "Found Version" on the posted pic, that its different from mine, mine just says  "Found Version" and thats it, no numbers or nothing. 

Trying to think of what may be causing issue, i have downloaded some stuff on here that require python and some other stuff, was the FairGame GPU tracker/notify/checkout bot for amazon. Only other thing i snagged off github. 

I did the above though and still get same issue with putting windows in local/bin and then the 1.3.0.b version, here is log from the 1.3.0.b 

[media-downloader] Running in portable mode
[media-downloader] Download path: C:/Users/Slider/Desktop/MediaDownloader-1.3.0a/Downloads
[media-downloader] Checking installed version of OpenSSL
[media-downloader] Found version: 
[media-downloader] Start Downloading youtube-dl ... ...
[media-downloader] Download Failed: TLS initialization failed
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: 4.3.2-2021-02-27-full_build-www.gyan.dev

Again though if u see on the Found Version mine is blank compared to the above picture posted, would that help point to what could be issue ? Sorry for slow replies.

**Comment by mhogomchungu** [comment] 2021-05-05 05:36
The blank found version for OpenSSL means no SSL support was found[1]. OpenSSL support is provided by two DLL that are already there in the app folder and they are named "libcrypto-1_1.dll" and "libssl-1_1.dll".

[1] https://doc.qt.io/qt-5/qsslsocket.html#sslLibraryVersionString

**Comment by slider6996** [comment] 2021-05-05 06:00
Hm alright, ya idk what could be causing issue then, i feel strongly its something on my end since im only one having this issue just not sure whats causing the issue, anyway for me to somehow send/post a logfile of whats installed on my pc that could be causing the issue? May be tomorrow morning before i can reply but ya, hoping i can figure this out. Thank yall so far for the assistance.

**Comment by juwala63** [comment] 2021-05-05 09:32
Try to (temporarilly) disable firewall. (may be block connection). 
If that were the case, you would then have to add the appropriate rule to it.

**Comment by mhogomchungu** [comment] 2021-05-05 10:04
The issue here is similar to this one[1] and their problem went away after updating OpenSSL to version 1.1.1j but OP here still has the problem even after updating OpenSSL.

This project uses only MinGW binaries it has no external dependencies as far as i know.

slider6996, do you restart your computer before testing?

[1] https://forum.qt.io/topic/122993/tls-initialization-failed-only-on-a-particular-machine

**Comment by slider6996** [comment] 2021-05-05 12:47
Alright was just seeing, hm ya im kinda stumped on what issue is, if there is a way to show u what i have installed on pc i can share.

**Comment by mhogomchungu** [comment] 2021-05-05 14:16
Why we are wondering why MediaDownloader is failing to pick up OpenSSL in your system, did you succeed in making it seeing youtube-dl by manually downloading it and placing it in in the "local/bin" subfolder located in the MediaDownloader's application folder?

**Comment by slider6996** [comment] 2021-05-06 01:31
On the youtube-dl on githup, which one of the files do i download and put in their is a few to choose from.

Source (.zip)
Source (.tar.gz)
PyPi
Ubuntu PPA
Arch AUR
Slackware SlackBuild
openSUSE
Windows Installer
Windows Portable

And which one do i choose and then what file/files inside, just asking so i know for sure and being thorough. And yes i did restart pc also to check and still was a no go.

**Comment by mhogomchungu** [comment] 2021-05-06 05:58
A link for windows version is this[1] one and this is the one you should use. Download it and put it in the "local/bin" folder. Create both folders if they are not in the MediaDownloader application folder.

The download page for the latest version is this[2] one and i am adding it here for completeness.

[1] https://github.com/ytdl-org/youtube-dl/releases/download/2021.04.26/youtube-dl.exe

[2] https://github.com/ytdl-org/youtube-dl/releases/tag/2021.04.26

**Comment by slider6996** [comment] 2021-05-10 15:10
Hey sorry about he super slow reply, real life and all. So here is update, made progress but idk if its good progress. Downloaded the youtube-dl linked above ( the exe ) i put it in the last verison that was posted on here of Media downloader which was the B version i believe, got new error, 2 actually. First one is a pop up saying

Youtube-dl.exe System error

The code excuction cannot process because MSVCR100.dll was not found. Reinstalling the program may fix the problem. 

Now as far as i recall that means a microsoft visual studios type thing right? I have all installed im pretty sure and this is the new log now with that error.

[media-downloader] Running in portable mode
[media-downloader] Download path: C:/Users/Slider/Desktop/MediaDownloader-1.3.0b/Downloads
[media-downloader] Checking installed version of OpenSSL
[media-downloader] Found version: 
[media-downloader] Checking installed version of youtube-dl
[media-downloader] Failed to find version information, make sure "youtube-dl" is installed and works properly
[media-downloader] Error: engines::defaultEngine: Unknown Engine: 
[media-downloader] Error: engines::defaultEngine: Unknown Engine: 
[media-downloader] Checking installed version of ffmpeg
[media-downloader] Found version: 4.3.2-2021-02-27-full_build-www.gyan.dev
[media-downloader] Error: engines::defaultEngine: Unknown Engine: 
[media-downloader] Error: engines::defaultEngine: Unknown Engine:

**Comment by mhogomchungu** [comment] 2021-05-12 12:35
Closing this one as fixed.

**Closed by mhogomchungu** 2021-05-12 12:35 UTC

**Comment by slider6996** [comment] 2021-06-09 02:27
Idk if its ok to post in a closed topic or if it will let me but i noticed i meant to ask how would i make it convert to mp3 ( audio only ) setting in preset options as the current one and default one use a weird format that i cant use to convert myself to mp3 and noticed in my car that they wont even play ( some of them ) so was curious what the preset code would be for just audio and mp3 only please.

**Comment by mhogomchungu** [comment] 2021-06-09 06:44
This[1] FAQ has an explanation on how to download and automatically save audio only media as mp3. Will set this option as the default in the next version.

The long explanation for why downloaded media have that ending is here[2]. In short, the default youtube-dl behavior is creating files that are in a format of ```%(title)s-%(id)s.%(ext)s```
and ```id``` is the part you do not want.

This[3] FAQ entry has steps to make to remove the "id" component.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#2-how-to-add-custom-commands-to-preset-list

[2] https://github.com/ytdl-org/youtube-dl#output-template

[3] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#3-how-to-make-downloaded-media-not-have-weird-text-in-the-file-name
