### ISSUE TITLE
Download Failed(ErrorCode=1), ERROR: 'utf-8' codec can't decode byte...

### ISSUE THREAD

**Issue by SlitherySnekks** [mhogomchungu/media-downloader#402] opened 2024-05-15 23:15 UTC
Im getting this error on all the newly added music videos in my playlist that im trying to download. 

I'm rerunning the same settings that I used to use couple months back. 

--skip-on-existing

-f bestaudio -x --embed-thumbnail --audio-format mp3

yet now i get the error.

log for the download:
[media-downloader] cmd: "C:/Users/manch/AppData/Roaming/media-downloader/bin/yt-dlp.exe" "-f" "bestaudio" "-x" "--embed-thumbnail" "--audio-format" "mp3" "-f" "bestaudio" "-x" "--embed-thumbnail" "--audio-format" "mp3" "-f" "bestaudio" "-x" "--embed-thumbnail" "--audio-format" "mp3" "--newline" "--output-na-placeholder" "NA" "--compat-options" "2022" "--progress-template" "download:[download] downloaded_bytes:%(progress.downloaded_bytes)s ETA:%(progress.eta)s total_bytes_estimate:%(progress.total_bytes_estimate)s total_bytes:%(progress.total_bytes)s progress.speed:%(progress.speed)s filename:%(progress.filename)s" "--cookies" "C:/Users/manch/AppData/Roaming/Mozilla/Firefox/Profiles/dx84szuf.default-release/cookies.sqlite" "https://www.youtube.com/watch?v=odcM3LqvQoA" "--download-archive" "C:/Users/manch/AppData/Roaming/media-downloader/data/subscriptions_archive_file.txt"
ERROR: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1072, in main
  File "yt_dlp\__init__.py", line 1062, in _real_main
  File "yt_dlp\YoutubeDL.py", line 973, in __exit__
  File "yt_dlp\YoutubeDL.py", line 976, in close
  File "yt_dlp\YoutubeDL.py", line 969, in save_cookies
  File "functools.py", line 967, in __get__
  File "yt_dlp\YoutubeDL.py", line 4082, in cookiejar
  File "yt_dlp\cookies.py", line 103, in load_cookies
  File "yt_dlp\cookies.py", line 1308, in load
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
[13960] Failed to execute script '__main__' due to unhandled exception!
[media-downloader] Download Failed(ErrorCode=1)

**Comment by mhogomchungu** [comment] 2024-05-16 04:14
Do you use a config file? If yes, did you set it to use utf-8 encoding?

Option ```-ignore-config``` should have been on the list. Add it and see if it makes a difference.

**Comment by SlitherySnekks** [comment] 2024-05-16 11:51
> Do you use a config file? If yes, did you set it to use utf-8 encoding?
> 
> Option `-ignore-config` should have been on the list. Add it and see if it makes a difference.

I dont think I use a config file, no.

adding the option '-ignore-config' doesnt seem to change anything, tried in both get list and download options, as well as '--ignore-config'

**Comment by SlitherySnekks** [comment] 2024-05-16 23:06
> ```
> File "yt_dlp\cookies.py", line 103, in load_cookies
> File "yt_dlp\cookies.py", line 1308, in load
> File "codecs.py", line 322, in decode
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
> ```
> 
> Above output suggest the problem is with the cookie file you are using. Remove the "--cookies" option and see if the problem is still there.

I wasnt using '--cookies', is there another gui i need to do this in? or some config file?

**Comment by mhogomchungu** [comment] 2024-05-16 23:57
The "--cookies" option is in your output as seen in the image below.

Your output also suggests you are using a custom ```engine's default options``` because it does not contain options Media Downloader sets by default 
like "--ignore-config" and "-o".

![Screenshot_20240517_024808](https://github.com/mhogomchungu/media-downloader/assets/3496115/39372159-9b71-4a33-870c-cdd097222105)

**Comment by SlitherySnekks** [comment] 2024-05-17 00:07
> The "--cookies" option is in your output as seen in the image below.
> 
> Your output also suggests you are using a custom `engine's default options` because it does not contain options Media Downloader sets by default like "--ignore-config" and "-o".
> 
> ![Screenshot_20240517_024808](https://private-user-images.githubusercontent.com/3496115/331416355-39372159-9b71-4a33-870c-cdd097222105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MDQxMjIsIm5iZiI6MTcxNTkwMzgyMiwicGF0aCI6Ii8zNDk2MTE1LzMzMTQxNjM1NS0zOTM3MjE1OS05YjcxLTRhMzMtODcwYy1jZGQwOTcyMjIxMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMjM1NzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMyNTg2ZjE2YWQ1NmZmYjFhMzc1MjIyNDcwMjE1MDYyZTg2ODMxYThlNGVlMTM2NTQwMzUwZTBkMjcwZDdlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-wqpTweneBgldjTFJwFKsjp70FCENgNb5udC5XfYpL8)

must be the betterfox profile... do i edit the cookies.sqlite file?

**Comment by mhogomchungu** [comment] 2024-05-17 05:22
I do not think you can easily edit it because it is a binary file and not a text file.

Google to see if there is an extension that can read the file and change its contents.

The problem you are having is not with Media Downloader but with yt-dlp not liking your cookies file and i see two solutions here and they are:-

1. Do not use the cookies file.
2. Clear the current cookies file and replace it with new data you want and hope the new data will not contain characters yt-dlp does not like.

Closing this one since the problem is outside Media Downloader.

**Closed by mhogomchungu** 2024-05-17 05:22 UTC
